AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Api

Globals:
  Function:
    Timeout: 10

Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: APIExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
      Statement:
        - Effect: Allow
          Principal:
            Service: 'lambda.amazonaws.com'
          Action: 'sts:AssumeRole'
      Roles:
        - DynamoDBCrudPolicy

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: MyApi
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  GetProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: products.get
      Runtime: nodejs20.x
      MemorySize: 128
      Role: !GetAtt ExecutionRole.Arn
      Events:
        Event:
          Type: Api
          Properties:
            Method: GET
            Path: /products
            RestApiId: !Ref MyApi

  CreateOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: orders.create
      Runtime: nodejs20.x
      MemorySize: 128
      Role: !GetAtt ExecutionRole.Arn
      Events:
        Event:
          Type: Api
          Properties:
            Method: POST
            Path: /createOrder
            RestApiId: !Ref MyApi

  FinishOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: orders.finish
      Runtime: nodejs20.x
      MemorySize: 128
      Role: !GetAtt ExecutionRole.Arn
      Events:
        Event:
          Type: Api
          Properties:
            Method: POST
            Path: /finishOrder
            RestApiId: !Ref MyApi

  GetOrdersFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: orders.get
      Runtime: nodejs20.x
      MemorySize: 128
      Role: !GetAtt ExecutionRole.Arn
      Events:
        Event:
          Type: Api
          Properties:
            Method: GET
            Path: /orders
            RestApiId: !Ref MyApi

  GetRestaurantsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./dist
      Handler: restaurants.get
      Runtime: nodejs20.x
      MemorySize: 128
      Role: !GetAtt ExecutionRole.Arn
      Events:
        Event:
          Type: Api
          Properties:
            Method: GET
            Path: /restaurants
            RestApiId: !Ref MyApi
