name: Front

on:
  push:
    paths:
      - "packages/front/**"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm --filter front install

      - name: Build
        run: pnpm build:front
        env:
          CI: ""

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }} #poner en secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} #poner en secrets
          aws-region: us-east-1

      - name: Deploy to s3
        working-directory: ./packages/front
        run: |
          aws s3 sync build s3://wakeup-fullstack-challenge/
          aws cloudfront create-invalidation --distribution-id E1M5KJF9PNWSUC --paths "/*"
